project:
  type: website
  output-dir: ../docs

website:
  title: "Imaging the human auditory system"
  navbar:
    left:
      - href: http://sitek.github.io/talk-auditory-imaging
        text: Github page

format:
  html:
    theme: flatly
    css: styles.css

